apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-main
  labels:
    app: {{ .Release.Name }}
data:
  APP_COLOR: {{ .Values.config.main.appColor }}
  WELCOME_MESSAGE: {{ .Values.config.main.welcomeMessage }}
---
{{- if .Values.canary.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-canary
  labels:
    app: {{ .Release.Name }}-canary
data:
  APP_COLOR: {{ .Values.config.canary.appColor }}
  WELCOME_MESSAGE: {{ .Values.config.canary.welcomeMessage }}
{{- end }}